services:
  # Backend API Service
  - type: web
    name: ai-moderation-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://ai-moderation-frontend.onrender.com
    
  # Frontend React App
  - type: web
    name: ai-moderation-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-moderation-backend.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://ai-moderation-backend.onrender.com
      - key: NODE_ENV
        value: production

# Optional: Database (if using PostgreSQL)
# databases:
#   - name: ai-moderation-db
#     plan: starter
#     databaseName: ai_moderation
#     user: ai_moderation_user